### ISSUE TITLE
Always getting `Not found. Authentication passthru.`

### ISSUE THREAD

**Issue by hamxashahid** [m0n9oose/omniauth_openid_connect#18]
Hi,

sorry if I am missing something very basic but I think I need some help in configuring this gem with devise in my application; I am always getting `Not found. Authentication passthru.` error;

The url that devise upon clicking 'Sign In with OpenIdConnect' goes to is: `https://myapp.com/users/auth/openid_connect`

My config looks like below in config/initializers/devise.rb :

```ruby
config.omniauth :openid_connect, { 
name: :provider, 
scope: [:openid], 
response_type: :code, 
client_options: { 
    port: 443, 
    scheme: "https", 
    host: "staging-oauth.provider.com", 
    issuer: "https://staging-oauth.provider.com", 
    authorization_endpoint: "/oauth2/auth", 
    token_endpoint: "/oauth2/token", 
    identifier: 'CLIENT_ID', 
    secret: 'CLIENT_SECRET', 
    redirect_uri: "https://myapp.com/users/auth/openid_connect/callback", 
  }, 
}
```

I know I have added extra parameters in it but that's because I'm unsure of what exactly is required; I cant see any logs on the server as well so it means I am not hitting the correct endpoint or something

I have the following urls from provider available

issuer endpoint (https://staging-oauth.provider.com)
authorization endpoint (https://staging-oauth.provider.com/oauth2/auth)
token endpoint (https://staging-oauth.provider.com/oauth2/token)
also I have the client id and secret
Can you please help me ?

**Comment by m0n9oose** [comment]
Hey @hamxashahid 

Not sure if I can help you without seeing the code and test application.

First of all, I have checked my configuration and noticed that my config has `issuer` but not in `client_options`:

```ruby
name: :keycloak,
scope: Array(Quokka.config[:scope]),
response_type: :code,
discovery: true,
issuer: File.join(Quokka::Base.base_uri.to_s, 'auth', 'realms', 'master'),
client_options: Quokka.config
```

I would suggest to double check your configuration and read [this](https://github.com/m0n9oose/omniauth_openid_connect/blob/master/lib/omniauth/strategies/openid_connect.rb) to check your config structure and default values

P.S. `Quokka` is a proprietary tool, so don't waste your time looking for it

**Comment by hamxashahid** [comment]
Thanks alot for your reply, 

Yes I went through the gem's code and figured out correct config for `issuer` and `discovery` options; and it was all pretty smooth after that;

There are a couple of things I found and would like to highlight:

1 - The `name` attribute is not arbitary and needs to be `:openid_connect` otherwise it wont work
2 - The `issuer` property is very important and it should exactly match the provider's issuer link;
3 - The discovery option needs to be set to true if you face any JWT decode errors;

If you can kindly update the readme then I am sure somebody else's time would be saved;

Closing the issue :)

Cheers.

**Comment by ssoulless** [comment]
@hamxashahid I see a problem, you said that `name` attribute needs to be `:openid_coonnect` in order to work properly, but what if you want to use the gem with more providers that use OpenID?
