### ISSUE TITLE
Option response_mode is defined but not used

### ISSUE THREAD

**Issue by januszm** [m0n9oose/omniauth_openid_connect#29]
In lib/omniauth/strategies/openid_connect.rb option `response_mode` is defined but not used anywhere. And it should be used (if defined) in the `authorize_uri` method:

```ruby
module OmniAuth
  module Strategies
    class OpenIDConnect
      include OmniAuth::Strategy
      # ...
      option :state
      option :response_mode
```

```ruby
      def authorize_uri
        client.redirect_uri = redirect_uri
        opts = {
          response_type: options.response_type,
+          response_mode: options.response_mode,
          scope: options.scope,
          # ...
        }
        client.authorization_uri(opts.reject { |_k, v| v.nil? })
      end
```

This allows using this gem with servers/flows which use response_mode=form_post for example.

**Comment by m0n9oose** [comment]
@januszm please open a PR with link to this issue and make sure your changes covered with tests. Thanks!

**Comment by januszm** [comment]
@m0n9oose you got it: https://github.com/m0n9oose/omniauth_openid_connect/pull/30

**Comment by januszm** [comment]
BTW. `response_type=id_token` works fine, we may want to adjust the README in general.

**Comment by m0n9oose** [comment]
Feel free to open a PR for this as well
