### ISSUE TITLE
the openid_connect gem is restricted to version 0.12.0

### ISSUE THREAD

**Issue by clucas** [m0n9oose/omniauth_openid_connect#3]
If we want to use a more recent version of the openid_connect gem (1.1.5 is the current latest), we need to update the gem dependency for openid_connect.
I created a pool request to address it: https://github.com/m0n9oose/omniauth_openid_connect/pull/2

**Comment by gearnode** [comment]
@clucas We maintained a fork as new master of this library. You can found this version [here](https://github.com/jobteaser/omniauth_openid_connect).
