### ISSUE TITLE
Param code should only be required when response_type is code

### ISSUE THREAD

**Issue by januszm** [m0n9oose/omniauth_openid_connect#31]
There's a line of code in the callback phase which raises an error:

```ruby
return fail!(
  :missing_code,
  OmniAuth::OpenIDConnect::MissingCodeError.new(params['error'])
) unless params['code']
```

It looks like it should be executed only if `option :response_type` is set to code (default).

How about:

```ruby
return fail!(
  :missing_code,
  OmniAuth::OpenIDConnect::MissingCodeError.new(params['error'])
) unless (options.response_type == 'code' && params['code'])
```

Which could be (apart from extracting the condition to a method) be simplified to:

```ruby
return fail!(
  :missing_FIXME,
  OmniAuth::OpenIDConnect::MissingFIXMEError.new(params['error'])
) unless (params[options.response_type]) # e.g. params['id_token'] is present if response_type == 'id_token'
```

**Comment by m0n9oose** [comment]
But `unless params[options.response_type]` condition is incorrect if

> It looks like it should be executed only if option :response_type is set to code

I'd say we can go with 2nd option, but it's worth to consider extracting check to separate method or at least local variable to make this check a bit more clear, like

```ruby
valid_code = params.key?('code') && options.response_type == 'code'
return fail!(
  :missing_code,
  OmniAuth::OpenIDConnect::MissingCodeError.new(params['error'])
) unless valid_code
```

**Comment by januszm** [comment]
Sure, to keep it simple we can add support for id_token first, but later on we might want to support all possible grant types like this:

```ruby
SUPPORTED_GRANT_TYPES = %w[code id_token token].freeze

# e.g. for `id_token token`, it is valid if:
(SUPPORTED_GRANT_TYPES & params.keys).sort.join(' ') == options.response_type
```
