### ISSUE TITLE
Why is prompt set in configuration and not as an ad-hoc GET parameter?

### ISSUE THREAD

**Issue by camilo0365** [m0n9oose/omniauth_openid_connect#46]

**Comment by camilo0365** [comment]
@m0n9oose any reason why you're closing this?

**Comment by m0n9oose** [comment]
@camilo0365 yes. I'm closing this issue because you use the issues section as a forum without any additional explanation, and I can answer it "why not?"

**Comment by camilo0365** [comment]
@m0n9oose you're right. I'm new to contributing, and I've seen these type of questions in other repos. I didn't mean to criticize in any way. I'll make a better, more explained and argumented issue if that's okay :)

**Comment by m0n9oose** [comment]
@camilo0365, of course, that's okay, I'd say it would be great. Please feel free to open a new issue, describe what exactly is wrong.

If you have any ideas on how to improve the code - open a pull request with your changes with the detailed description, and we'll discuss it with others.

**Comment by camilo0365** [comment]
@m0n9oose Perfect! Thanks
