### ISSUE TITLE
Implicit Flow problems

### ISSUE THREAD

**Issue by hhorikawa** [m0n9oose/omniauth_openid_connect#56]
I've found some behaviours in the Implicit Flow that should be improved. I would like to report them.

 - response_type = 'id_token' is able to be used limited to definitely trusted OPs (Self-Issued OpenID Providers). Normally it should not be used. Instead, you have to specify ['id_token', 'token'] for the Implicit Flow.
 - The nonce is required. Therefore, the 'send_nonce' option value should be ignored on the Implicit Flow.
-Both of id_token and access token must be properly verified. One is not enough.

Regarding verification, how to use key needs to be improved.
 - On the Authorization Code Flow, you can use OP's public key or client secret that is specified by the response code's header. 
 - The other hand, you have to use the exact public key for validation on the Implicit Flow.
So, calling key_or_secret() from public_key() is not good.

Regards,
Hisashi.

**Comment by hhorikawa** [comment]
An implicit flow sample:
https://github.com/netsphere-labs/openid-connect-implicit-flow-rp-sample

**Comment by m0n9oose** [comment]
@hhorikawa can you open a PR with proposed changes?
