### ISSUE TITLE
Cannot find a way to use redirect_uri param

### ISSUE THREAD

**Issue by dznicol** [m0n9oose/omniauth_openid_connect#66]
This change suggests that it is possible to customize the redirect_uri by passing a param[:redirect_uri] at some point in the flow:

https://github.com/m0n9oose/omniauth_openid_connect/commit/5ce3b551d78ec781559f2fe5bb731c892cf42370#diff-8467ba16957a2513a82eb9fe781131df

I have tried adding this param alongwith with the initial redirect to /auth/openid_connect, for example:

`http://tenant1.localhost:5000/users/auth/openid_connect?redirect_uri=tenant1.localhost
`

However, this results in 2 redirect_uri parameters being sent in the redirect to the auth service, the URI in the query string above, plus the URI specified in config.

The end goal is to support multi-tenant sub-domains, using a single auth endpoint.

Given the commit above, should it be possible to specify a request_uri at request time rather than in fixed config?

**Comment by gcolson** [comment]
I agree with @dznicol. We should be able, at least, to set the `client_options.redirect_uri` as a proc in order to add parameters on the fly to the url or things like that. 
I also think that any parameter given to the request url should be added to the fixed callback url (ex. `https://host.com/path?param1=value1&param2=value2` as request url should give `https://host.com/path/callback?param1=value1&param2=value2` as callback url)

**Comment by makeready** [comment]
+1 for this feature (if it's supported by the openid connect protocol)

**Comment by makeready** [comment]
@dznicol the extra query parameters you give to omniauth in the initial request will come back to you as part of the state token. I called mine "landing_url" to avoid the name collision with the oauth redirect url, and I can access it at the callback endpoint via request.env['omniauth.params']['landing_url']

**Comment by makeready** [comment]
Using information held in the state token to control which page the user lands on should work most of the time. 

That said, it would still be pretty nice to be able to define the redirect url dynamically. In my case I have a central domain handling the oauth, after which I have to send the user to a different subdomain matching their account, and my cookies are subdomain specific, so another internal auth mechanism is needed for the subdomain redirect. With dynamic redirect uri support  in this gem (and if I can convince my provider to implement a wildcard whitelist on their side) I could have the user's subdomain manage the entire process. 

One thing I thought of is iterating over all my subdomains on boot, registering a provider for each, but that seems pretty clunky.

**Comment by masciugo** [comment]
@makeready have you ever found a way to do that? thank you

**Comment by raivil** [comment]
any updates on this issue?
I'd like to use dynamic callbacks uris as well, if possible.
