### ISSUE TITLE
Support for multiple response types

### ISSUE THREAD

**Issue by antons-** [m0n9oose/omniauth_openid_connect#67]
Currently, `response_type` can be either `code` or `id_token`.

Does this gem have support for multiple-valued response types, such as `id_token token`?

If so, what is the correct format for specifying them in the config? If not, can this functionality be added?

See the following for references:

- https://openid.net/specs/openid-connect-core-1_0.html#Authentication

**Comment by tgunaselan** [comment]
Below are the errors am getting for using multiple options in response_type. For both type of usage am getting the same error.

**Usage 1 : 'response_type' => 'id_token token'**

Error:

> Started POST "/users/auth/openid_connect" for 202.164.25.5 at 2020-09-09 20:43:57 +0000
> Processing by Gitlab::RequestForgeryProtection::Controller#index as HTML
> Parameters: {"authenticity_token"=>"[FILTERED]"}
> Completed 200 OK in 1ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms | Allocations: 169)
> Started GET "/-/metrics" for 127.0.0.1 at 2020-09-09 20:43:58 +0000
> Processing by MetricsController#index as HTML
> Completed 200 OK in 6ms (Views: 0.4ms | ActiveRecord: 0.0ms | Elasticsearch: 0.0ms | Allocations: 686)
> Started GET "/users/auth/openid_connect/callback?state=b390992f1d3f1903e068c390fa1b06c5&nonce=28e1cb711a56cc97c1adf6c0084c232a&token_type=Bearer&expires_in=3600&access_token=[FILTERED]&id_token=[FILTERED]" for 202.164.25.5 at 2020-09-09 20:44:00 +0000
> 
> NoMethodError (undefined method `[]' for nil:NilClass):


**Usage 2 : 'response_type' => 'id_token%20token'**

Error:

> Started POST "/users/auth/openid_connect" for 202.164.25.5 at 2020-09-09 20:54:03 +0000
> Processing by Gitlab::RequestForgeryProtection::Controller#index as HTML
> Parameters: {"authenticity_token"=>"[FILTERED]"}
> Completed 200 OK in 1ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms | Allocations: 169)
> Started GET "/users/auth/openid_connect/callback?state=85282b6c69c5f8b6abbe4ce8a7e5541c&nonce=47fa75eafa91af8f96523a23f7814d7f&token_type=Bearer&expires_in=3600&access_token=[FILTERED]&id_token=[FILTERED]" for 202.164.25.5 at 2020-09-09 20:54:05 +0000
> 
> NoMethodError (undefined method `[]' for nil:NilClass):

**Comment by tgunaselan** [comment]
Hello Team,

May i know why this issue was closed ?
