### ISSUE TITLE
Support custom claims?

### ISSUE THREAD

**Issue by yoonwaiyan** [m0n9oose/omniauth_openid_connect#76]
I've traced the code and the PRs for the claims but they're last edited 6 years ago at least. I'm not sure how the specification changed over time but there are many more attributes as listed in the [latest specs](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims), and I would like to add some other attributes than the specs (are they allowed?), as you can see from [doorkeeper gem](https://github.com/doorkeeper-gem/doorkeeper-openid_connect#claims) that we can customize the claims to return to clients.

Suggesting maybe we can have another configuration block for the claims mapping.

**Comment by iankoulski** [comment]
I have a situation where the ODIC server returns the email in a field named "mail" instead of "email" and that causes the authentication to fail. I am unable to modify the configuration of the OIDC server. It would really help if this gem was able to configure claims mapping. +1 on this feature.
