### ISSUE TITLE
Add support for OmniAuth 2.0

### ISSUE THREAD

**Issue by shmokmt** [m0n9oose/omniauth_openid_connect#81]
I think it is safer to support OmniAuth2.0 for this gem as well like https://github.com/omniauth/omniauth-openid/pull/44 .

See Also:
https://github.com/omniauth/omniauth/releases
https://github.com/heartcombo/devise/issues/5326#issuecomment-758819662

**Comment by travisofthenorth** [comment]
@m0n9oose do you mind taking a look at these and related PRs. It would be great to get this gem upgraded so that applications using it can upgrade omniauth and address related security issues.
