### ISSUE TITLE
Support for multiple response types

### ISSUE THREAD

**Issue by tgunaselan** [m0n9oose/omniauth_openid_connect#83]
Currently, response_type can be either code or id_token.

Does this gem have support for multiple-valued response types, such as id_token token?

If so, what is the correct format for specifying them in the config? If not, can this functionality be added?

See the following for references:

https://openid.net/specs/openid-connect-core-1_0.html#Authentication

**Comment by tgunaselan** [comment]
For implicit and hybrid flow, enabling "token" along with code/id_token would be much helpful.

**Comment by tgunaselan** [comment]
Any Update.

**Comment by tgunaselan** [comment]
Hello, Is this request need any further reasons or inputs from my end ?

**Comment by tgunaselan** [comment]
Pinging here to enable this request open.

**Comment by gwright** [comment]
I'd like to reopen this topic.  I'm looking to implement the hybrid flow ("code id_token") and that fails with the current version of the gem  the `#valid_response_type?` method because it assumes a single configured value for `response_type`.  I'm not sure if that is the only difficulty but I'm going to see if I can get this to work in a fork.

**Comment by kreintjes** [comment]
Same problem over here. Our provider recommends the hybrid flow ("code id_token") in our situation. We cannot currently achieve this with this gem. Is there any solution for this or are there plans to implement this?

**Comment by davidwessman** [comment]
I do not think anyone is working actively unless it is for their own usage.
So please try to make a PR 🙂

**Comment by davidwessman** [comment]
I guess this is what you are looking for?
https://github.com/omniauth/omniauth_openid_connect/pull/139

Maybe try it out, see if it works for you?
