### ISSUE TITLE
Having problem to debug connection issue

### ISSUE THREAD

**Issue by SebTardif** [m0n9oose/omniauth_openid_connect#85]
Maybe everybody else knows this, but I tried to use OIDC with gitlab and keycloak and I cannot find a single log entry showing that something is happening even if I click the sso button on the gitlab ui.

I looked at the code base of this project and I also see now line about outputting log.

I wonder how people approach this, and if that would make sense that the README.md have some words about debugging the thing.

**Comment by stanhu** [comment]
It's certainly not easy at the moment. I mostly debug with a GitLab Development Kit and use `puts` and `byebug` to insert breakpoints.

OmniAuth appears to have a `log` method that could be used to insert more debug info: https://github.com/omniauth/omniauth/blob/a62d36b3f847e0e55b077790112e96950c35085a/lib/omniauth/strategy.rb#L161-L164
