### ISSUE TITLE
Please refer to the upgraded repository

### ISSUE THREAD

**Issue by hhorikawa** [m0n9oose/omniauth_openid_connect#99]
I've merged the many fixes scattered on many repositories, and I've provided a version that works with the latest environment and specs.
 - OmniAuth2
 - Ruby 3
 - Supports the following: OpenID Connect Core 1.0 the Authorization Code Flow and the Implicit Flow. OpenID Connect RP-Initiated Logout 1.0.

If you agree, please write on the README to direct visitors to the new repository.
https://github.com/netsphere-labs/omniauth-openid-connect/

I'm always looking for developers, contributors. Thanks.

**Comment by Eric-Guo** [comment]
omniauth-openid-connect and omniauth_openid_connect is now quite different, if any one coming in future just want to using current master branch of omniauth_openid_connect, add [TokenVerifier](https://github.com/thape-cn/omniauth_openid_connect-demo/commit/13182c0e295b1c0487c2a523eaea8d94ba6b22ff) maybe enough.

**Comment by Eric-Guo** [comment]
@m0n9oose I can take `omniauth_openid_connect` maintain if no other more suitable, at least I using this gem in two project and can testing the PR in future.
